[package]
name = "lokpassrs"
version = "0.1.0"
description = "password manager"
authors = ["soerenlemke <soerenlemke@gmx.de>"]
license = "MIT"
edition = "2024"

[dependencies]
arboard = "3.5.0"
crossterm = "0.29.0"
ratatui = "0.29.0"
