[package]
name = "lokpassrs"
version = "0.1.0"
description = "password manager"
authors = ["soerenlemke <soerenlemke@gmx.de>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
itertools = "0.14.0"
unicode-width = "0.1.14"
fakeit = "1.3.0"